# https://golangci-lint.run/usage/quick-start/
run:
  concurrency: 4
  timeout: 5m
issues:
  exclude-dirs:
    - vendor
linters:
  enable:
    - testifylint
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj/pkg
  testifylint:
    enable-all: true
    disable:
      - float-compare
