# https://golangci-lint.run/usage/quick-start/
run:
  concurrency: 4
  timeout: 5m
  skip-dirs:
    - vendor
  build-tags:
    - api
    - cli
    - cron
    - executor
    - examples
    - functional
linters:
  enable:
    - deadcode
    - errcheck
    - goimports
    - gci
    - gofumpt
    - gosimple
    - govet
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj/pkg
