version: "2"
run:
  concurrency: 4
linters:
  enable:
    - testifylint
  settings:
    testifylint:
      enable-all: true
      disable:
        - float-compare
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/argoproj/pkg/v2
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
